### PR TITLE
[fix] locales moulinette go into locale folder

### PR DESCRIPTION
**Pull request by zamentur**
The place where locales are put is /usr/share/moulinette/locale and not locales !

### CODE REVIEW

**Comment by Psycojoker** [comment]
It's weird that it's named "locales" in moulinette then :o

**Comment by zamentur** [comment]
I am not sure but maybe it's due to the default python build https://github.com/YunoHost/moulinette/blob/unstable/debian/rules

The is no install files like in other packages !

I have seen this by testing the "info" pr on moulinette.

**Comment by Psycojoker** [comment]
It looks like we have the same bug here then, no? https://github.com/YunoHost/ynh-dev/pull/41/files#diff-9b0364a5bf0552f669d4a9953c7625d8R269

**Comment by zamentur** [comment]
No because the packag is not created with the same method there is an install file in yunohost package

**Comment by Psycojoker** [comment]
Ok, let's merge.

**Pull request merged**
