### PR TITLE
Developer environment README improvements

### PR DESCRIPTION
**Pull request by decentral1se**
Closes https://github.com/YunoHost/issues/issues/1353.

So, I am sorry it is such a big patch but on the good side, I really didn't change any of the actual content. This change brings a table of contents and some clarification on which environment to choose (local, remote) dependending on your circumstances. Also versions were added and improved Markdown formatting.

The easiest is to just review the rendered markdown file:

> https://github.com/decentral1se/ynh-dev/blob/e96765f4fe8cff3b861caee437655f702e5e617f/README.md

Please let me know what you think then!

### CODE REVIEW

**Comment by decentral1se** [comment]
> I propose to add a few more comments about Virtualbox vs LXC, and local vs remote

Nice! :clap:

**Comment by Psycojoker** [comment]
I wonder if we shouldn't also integrate documentation regarding the virtualbox version of ynh-dev in this README at this point https://github.com/YunoHost/ynh-dev/tree/virtualbox

It was the old version but it's still working pretty fine for me (I'm still using it daily for my dev because lxc is just a PITA to configure for me and the other one basically just works without any problems for me).

Anyway, thanks a lot for this contribution :)

**Comment by decentral1se** [comment]
@Psycojoker, AFAICT, the commands used in that document you linked do not exist in the `ynh-dev` script anymore, for example, `ynh-dev create-env`, `ynh-dev run`, etc. I wouldn't want to confuse users with this issue. I'm glad it is working for you though :) 

I'll probably leave this PR as is for now if that is OK.

Off to setup this VPS server then ;)

**Comment by Psycojoker** [comment]
@decentral1se actually it's in another branch, so if you clone this other branch you'll the get "virtualbox" version of ynh-dev, so that would be a mention of "if you use this other branch" etc...

**Comment by decentral1se** [comment]
> actually it's in another branch

Ah right! Please see https://github.com/YunoHost/ynh-dev/pull/50/commits/3f80c88316b40e2f04c8957ba4b125ed5e8677a5 then.

New rendered version in:

> https://github.com/YunoHost/ynh-dev/blob/3f80c88316b40e2f04c8957ba4b125ed5e8677a5/README.md

Can we merge this then?

**Comment by decentral1se** [comment]
Bump :shark: :shark: :shark:

**Comment by alexAubin** [comment]
Yolomergin then o/ Thanks again for contributing to the doc !

**Pull request merged**
